# Railway 部署配置文件
version: 2

services:
  api:
    image: team-api
    build:
      context: .
      dockerfile: Dockerfile
    variables:
      ASPNETCORE_ENVIRONMENT: Production
      PORT: 8080
    healthcheck:
      path: /health
      interval: 30s
      timeout: 10s
      retries: 3