// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.API.Models.EfModel;

public partial class AttributeValue
{
    public int Id { get; set; }

    public string Value { get; set; }

    public string HexCode { get; set; }

    public int? AttributeId { get; set; }

    public int? SellersId { get; set; }

    public virtual Attribute Attribute { get; set; }

    public virtual ICollection<ProductAttributeValue> ProductAttributeValues { get; set; } = new List<ProductAttributeValue>();

    public virtual Seller Sellers { get; set; }
}