// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.API.Models.EfModel;

public partial class Attribute
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int? SellersId { get; set; }

    public bool IsApproved { get; set; }

    public virtual ICollection<AttributeValue> AttributeValues { get; set; } = new List<AttributeValue>();

    public virtual Seller Sellers { get; set; }
}