// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Team.API.Models.EfModel;

public partial class Carrier
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Contact { get; set; }

    public DateTime? CreatedAt { get; set; }

    // 暫時移除 IsActive 和 Status，等資料庫有這些欄位後再加回
    // public bool IsActive { get; set; } = true;
    // public string? Status { get; set; }

    // 使用 NotMapped 屬性來提供預設行為
    [NotMapped]
    public bool IsActive { get; set; } = true;

    public virtual ICollection<Shipment> Shipments { get; set; } = new List<Shipment>();
}