// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.API.Models.EfModel;

public partial class ContentPublishingSchedule
{
    public int Id { get; set; }

    public string ContentType { get; set; }

    public int ContentId { get; set; }

    public string ActionType { get; set; }

    public DateTime ScheduledTime { get; set; }

    public string Status { get; set; }

    public DateTime? ExecutedAt { get; set; }

    public string ErrorMessage { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? CreatedBy { get; set; }

    public virtual User CreatedByNavigation { get; set; }
}