// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.API.Models.EfModel;

public partial class Coupon
{
    public int Id { get; set; }

    public string Title { get; set; }

    public int DiscountAmount { get; set; }

    public string DiscountType { get; set; }

    public int MinSpend { get; set; }

    public int? ApplicableLevelId { get; set; }

    public int? CategoryId { get; set; }

    public int? SellersId { get; set; }

    public int? UsageLimit { get; set; }

    public int UsedCount { get; set; }

    public bool IsActive { get; set; }

    public DateTime ExpiredAt { get; set; }

    public DateTime StartAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual MembershipLevel ApplicableLevel { get; set; }

    public virtual CouponCategory Category { get; set; }

    public virtual ICollection<CouponDispatchTask> CouponDispatchTasks { get; set; } = new List<CouponDispatchTask>();

    public virtual ICollection<CouponNotification> CouponNotifications { get; set; } = new List<CouponNotification>();

    public virtual ICollection<CouponReturnHistory> CouponReturnHistories { get; set; } = new List<CouponReturnHistory>();

    public virtual ICollection<MemberCoupon> MemberCoupons { get; set; } = new List<MemberCoupon>();

    public virtual ICollection<MembershipLevel> MembershipLevels { get; set; } = new List<MembershipLevel>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual Seller Sellers { get; set; }
}