// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.API.Models.EfModel;

public partial class MemberFollow
{
    public int Id { get; set; }

    public int? FollowerId { get; set; }

    public int? FollowingId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Member Follower { get; set; }

    public virtual Member Following { get; set; }
}