// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.API.Models.EfModel;

public partial class MemberCoupon
{
    public int Id { get; set; }

    public int? MemberId { get; set; }

    public int? CouponId { get; set; }

    public string Status { get; set; }

    public DateTime AssignedAt { get; set; }

    public DateTime? UsedAt { get; set; }

    public int? OrderId { get; set; }

    public bool ExpirationReminderSent { get; set; }

    public string VerificationCode { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Coupon Coupon { get; set; }

    public virtual Member Member { get; set; }

    public virtual Order Order { get; set; }
}