// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.API.Models.EfModel;

public partial class MemberProfile
{
    public int Id { get; set; }

    public int MembersId { get; set; }


    public string Name { get; set; }

    public string Gender { get; set; }

    public DateOnly BirthDate { get; set; }

    public string ProfileImg { get; set; }

    public string MemberAccount { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    //修改
    public virtual Member Members { get; set; }
}