// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Team.API.Models.EfModel;

public partial class Notification
{
    public int Id { get; set; }

    public int? MemberId { get; set; }

    public int? SellerId { get; set; }

    public string Category { get; set; }

    public string Message { get; set; }

    public DateTime SentAt { get; set; }

    public string EmailAddress { get; set; }

    public string EmailStatus { get; set; }

    public DateTime? EmailSentAt { get; set; }

    public int EmailRetry { get; set; }

    public string Channel { get; set; }

    public bool IsDeleted { get; set; }

    //// 新增的資料庫欄位
    //public DateTime? ScheduledAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    //// 格式化屬性（不映射到資料庫）
    //[NotMapped]
    //public string FormattedScheduledAt => ScheduledAt?.ToString("yyyy-MM-dd HH:mm:ss");

    [NotMapped]
    public string FormattedCreatedAt => CreatedAt.ToString("yyyy-MM-dd HH:mm:ss");

    [NotMapped]
    public string FormattedUpdatedAt => UpdatedAt.ToString("yyyy-MM-dd HH:mm:ss");

    public virtual Member Member { get; set; }

    public virtual Seller Seller { get; set; }
}