// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.API.Models.EfModel;

public partial class OfficialPost
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string SeoTitle { get; set; }

    public string SeoDescription { get; set; }

    public string Content { get; set; }

    public string CoverImage { get; set; }

    public string Category { get; set; }

    public int? ReadingTime { get; set; }

    public string Status { get; set; }

    public DateTime? PublishedAt { get; set; }

    public int CreatedBy { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual ICollection<OfficialPostComment> OfficialPostComments { get; set; } = new List<OfficialPostComment>();

    public virtual ICollection<OfficialPostImage> OfficialPostImages { get; set; } = new List<OfficialPostImage>();
}