// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.API.Models.EfModel;

public partial class Order
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public int? SellersId { get; set; }

    public int AddressId { get; set; }

    public string RecipientName { get; set; }

    public string PhoneNumber { get; set; }

    public string City { get; set; }

    public string District { get; set; }

    public string AddressDetail { get; set; }

    public string DeliveryMethod { get; set; }

    public decimal ShippingFee { get; set; }

    public int? CouponId { get; set; }

    public string DiscountType { get; set; }

    public decimal? DiscountAmount { get; set; }

    public bool? FreeShipping { get; set; }

    public int? UsedPoints { get; set; }

    public decimal? PointsDeductAmount { get; set; }

    public decimal SubtotalAmount { get; set; }

    public decimal TotalAmount { get; set; }

    public string PaymentMethod { get; set; }

    public string PaymentStatus { get; set; }

    public string OrderStatus { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual MemberAddress Address { get; set; }

    public virtual Coupon Coupon { get; set; }

    public virtual Member Member { get; set; }

    public virtual ICollection<MemberCoupon> MemberCoupons { get; set; } = new List<MemberCoupon>();

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual ICollection<OrderNotification> OrderNotifications { get; set; } = new List<OrderNotification>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual ICollection<Return> Returns { get; set; } = new List<Return>();

    public virtual Seller Sellers { get; set; }

    public virtual ICollection<Shipment> Shipments { get; set; } = new List<Shipment>();
}