// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.API.Models.EfModel;

public partial class PostLike
{
    public int Id { get; set; }

    public int PostId { get; set; }

    public int MembersId { get; set; }

    public virtual Member Members { get; set; }

    public virtual Post Post { get; set; }
}