// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.API.Models.EfModel;

public partial class Return
{
    public int Id { get; set; }

    public int? MemberId { get; set; }

    public int? OrderId { get; set; }

    public int? RefundedPoints { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Member Member { get; set; }

    public virtual Order Order { get; set; }
}