// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.API.Models.EfModel;

public partial class SellerReturnInfo
{
    public int Id { get; set; }

    public int SellersId { get; set; }

    public string ContactName { get; set; }

    public string ContactPhone { get; set; }

    public string ReturnAddress { get; set; }

    public string City { get; set; }

    public string District { get; set; }

    public string ZipCode { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Seller Sellers { get; set; }
}