// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.API.Models.EfModel;

public partial class SellerDocument
{
    public int Id { get; set; }

    public int SellersId { get; set; }

    public string DocumentType { get; set; }

    public string FilePath { get; set; }

    public DateTime UploadedAt { get; set; }

    public bool Verified { get; set; }

    public DateTime? VerifiedAt { get; set; }

    public virtual Seller Sellers { get; set; }
}