// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.API.Models.EfModel;

public partial class Seller
{
    public int Id { get; set; }

    public int? MembersId { get; set; }

    public string RealName { get; set; }

    public string IdNumber { get; set; }

    public string ApplicationStatus { get; set; }

    public DateTime AppliedAt { get; set; }

    public DateTime? ApprovedAt { get; set; }

    public string RejectedReason { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<AttributeValue> AttributeValues { get; set; } = new List<AttributeValue>();

    public virtual ICollection<Attribute> Attributes { get; set; } = new List<Attribute>();

    public virtual ICollection<ChatRoom> ChatRooms { get; set; } = new List<ChatRoom>();

    public virtual ICollection<CouponNotification> CouponNotifications { get; set; } = new List<CouponNotification>();

    public virtual ICollection<Coupon> Coupons { get; set; } = new List<Coupon>();

    public virtual Member Members { get; set; }

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual ICollection<OrderNotification> OrderNotifications { get; set; } = new List<OrderNotification>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    public virtual ICollection<RestockNotification> RestockNotifications { get; set; } = new List<RestockNotification>();

    public virtual ICollection<SellerBankAccount> SellerBankAccounts { get; set; } = new List<SellerBankAccount>();

    public virtual ICollection<SellerDocument> SellerDocuments { get; set; } = new List<SellerDocument>();

    public virtual ICollection<SellerReturnInfo> SellerReturnInfos { get; set; } = new List<SellerReturnInfo>();
}