// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.API.Models.EfModel;

public partial class Shipment
{
    public int Id { get; set; }

    public int OrderId { get; set; }

    public string Status { get; set; }

    public int? CarrierId { get; set; }

    public string TrackingNumber { get; set; }

    public DateTime? ShippedAt { get; set; }

    public DateTime? DeliveredAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Carrier Carrier { get; set; }

    public virtual Order Order { get; set; }
}