// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.API.Models.EfModel;

public partial class SocialLogin
{
    public int Id { get; set; }

    public int MembersId { get; set; }

    public string Provider { get; set; }

    public string ProviderUserId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Member Members { get; set; }
}