// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.API.Models.EfModel;

public partial class User
{
    public int Id { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public int RoleId { get; set; }

    public bool IsActive { get; set; }

    public bool MustSetPassword { get; set; }

    public DateTime? LastLoginAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<AdminInvitation> AdminInvitationCreatedByNavigations { get; set; } = new List<AdminInvitation>();

    public virtual ICollection<AdminInvitation> AdminInvitationUsers { get; set; } = new List<AdminInvitation>();

    public virtual ICollection<Banner> Banners { get; set; } = new List<Banner>();

    public virtual ICollection<ChatRoom> ChatRooms { get; set; } = new List<ChatRoom>();

    public virtual ICollection<ContentPublishingSchedule> ContentPublishingSchedules { get; set; } = new List<ContentPublishingSchedule>();

    public virtual ICollection<CouponDispatchTask> CouponDispatchTasks { get; set; } = new List<CouponDispatchTask>();

    public virtual ICollection<OfficialPost> OfficialPosts { get; set; } = new List<OfficialPost>();

    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();

    public virtual UserRole Role { get; set; }

    public virtual ICollection<UserAuditLog> UserAuditLogTargetUsers { get; set; } = new List<UserAuditLog>();

    public virtual ICollection<UserAuditLog> UserAuditLogUsers { get; set; } = new List<UserAuditLog>();
}