// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.API.Models.EfModel;

public partial class UserAuditLog
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int? TargetUserId { get; set; }

    public string ActionType { get; set; }

    public string Description { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual User TargetUser { get; set; }

    public virtual User User { get; set; }
}