// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Team.Backend.Models.EfModel;

public partial class Carrier
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Contact { get; set; }

    public DateTime? CreatedAt { get; set; }

    public bool IsActive { get; set; } = true;

    public virtual ICollection<Shipment> Shipments { get; set; } = new List<Shipment>();
}