// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.Backend.Models.EfModel;

public partial class CartItem
{
    public int Id { get; set; }

    public int CartId { get; set; }

    public int ProductId { get; set; }

    public int AttributeValueId { get; set; }

    public int Quantity { get; set; }

    public decimal PriceAtAdded { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ProductAttributeValue AttributeValue { get; set; }

    public virtual Cart Cart { get; set; }

    public virtual Product Product { get; set; }
}