// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.Backend.Models.EfModel;

public partial class Category
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    // 移除重複的導航屬性，只保留一對多關係
    public virtual ICollection<SubCategory> SubCategories { get; set; } = new List<SubCategory>();
}