// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.Backend.Models.EfModel;

public partial class ChatRoom
{
    public int Id { get; set; }

    public int? MemberId { get; set; }

    public int? SellerId { get; set; }

    public int? AdminId { get; set; }

    public string RoomName { get; set; }

    public string Status { get; set; }

    public DateTime? LastMessageAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual User Admin { get; set; }

    public virtual ICollection<ChatMessage> ChatMessages { get; set; } = new List<ChatMessage>();

    public virtual Member Member { get; set; }

    public virtual Seller Seller { get; set; }
}