// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.Backend.Models.EfModel;

public partial class ChatMessage
{
    public int Id { get; set; }

    public int ChatRoomId { get; set; }

    public string SenderType { get; set; }

    public int SenderId { get; set; }

    public string MessageType { get; set; }

    public string Content { get; set; }

    public string FileUrl { get; set; }

    public bool? IsReadMember { get; set; }

    public bool? IsReadSeller { get; set; }

    public bool? IsReadAdmin { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ChatRoom ChatRoom { get; set; }
}