// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.Backend.Models.EfModel;

public partial class CommentLike
{
    public int Id { get; set; }

    public int CommentId { get; set; }

    public string CommentType { get; set; }

    public int MembersId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Member Members { get; set; }
}