// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.Backend.Models.EfModel;

public partial class ContentStatistic
{
    public int Id { get; set; }

    public string ContentType { get; set; }

    public int ContentId { get; set; }

    public int? ViewCount { get; set; }

    public int? LikeCount { get; set; }

    public int? CommentCount { get; set; }

    public int? ShareCount { get; set; }

    public DateTime? LastUpdated { get; set; }
}