// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.Backend.Models.EfModel;

public partial class CouponDispatchTask
{
    public int Id { get; set; }

    public int CouponId { get; set; }

    public string TaskName { get; set; }

    public string DispatchType { get; set; }

    public string TargetCriteria { get; set; }

    public DateTime ScheduledTime { get; set; }

    public string Status { get; set; }

    public int ProgressCount { get; set; }

    public int TotalTargetCount { get; set; }

    public string ErrorMessage { get; set; }

    public int? CreatedByAdminId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Coupon Coupon { get; set; }

    public virtual User CreatedByAdmin { get; set; }
}