

// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.Backend.Models.EfModel;

public partial class Member
{
    public int Id { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public string RegisteredVia { get; set; }

    public bool IsEmailVerified { get; set; }

    public bool IsActive { get; set; }

    public int Level { get; set; }

    public bool Role { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<Cart> Carts { get; set; } = new List<Cart>();

    public virtual ICollection<ChatRoom> ChatRooms { get; set; } = new List<ChatRoom>();

    public virtual ICollection<CommentLike> CommentLikes { get; set; } = new List<CommentLike>();

    public virtual ICollection<CouponNotification> CouponNotifications { get; set; } = new List<CouponNotification>();

    public virtual ICollection<CouponReturnHistory> CouponReturnHistories { get; set; } = new List<CouponReturnHistory>();

    public virtual MembershipLevel LevelNavigation { get; set; }

    public virtual ICollection<MemberAddress> MemberAddresses { get; set; } = new List<MemberAddress>();

    public virtual ICollection<MemberCoupon> MemberCoupons { get; set; } = new List<MemberCoupon>();

    public virtual ICollection<MemberFollow> MemberFollowFollowers { get; set; } = new List<MemberFollow>();

    public virtual ICollection<MemberFollow> MemberFollowFollowings { get; set; } = new List<MemberFollow>();
     
    //更改
    public virtual MemberProfile Profile { get; set; }

    public virtual MemberStat MemberStat { get; set; }

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual ICollection<OfficialPostComment> OfficialPostComments { get; set; } = new List<OfficialPostComment>();

    public virtual ICollection<OrderAddress> OrderAddresses { get; set; } = new List<OrderAddress>();

    public virtual ICollection<OrderNotification> OrderNotifications { get; set; } = new List<OrderNotification>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<PasswordResetCode> PasswordResetCodes { get; set; } = new List<PasswordResetCode>();

    public virtual ICollection<PointsLogError> PointsLogErrors { get; set; } = new List<PointsLogError>();

    public virtual ICollection<PointsLog> PointsLogs { get; set; } = new List<PointsLog>();

    public virtual ICollection<PostComment> PostComments { get; set; } = new List<PostComment>();

    public virtual ICollection<PostLike> PostLikes { get; set; } = new List<PostLike>();

    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();

    public virtual ICollection<Return> Returns { get; set; } = new List<Return>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual Seller Seller { get; set; }

    public virtual ICollection<Session> Sessions { get; set; } = new List<Session>();

    public virtual ICollection<SocialLogin> SocialLogins { get; set; } = new List<SocialLogin>();

    public virtual ICollection<VerificationCode> VerificationCodes { get; set; } = new List<VerificationCode>();
}