// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.Backend.Models.EfModel;

public partial class MemberAddress
{
    public int Id { get; set; }

    public int MembersId { get; set; }

    public string RecipientName { get; set; }

    public string PhoneNumber { get; set; }

    public string City { get; set; }

    public string District { get; set; }

    public string ZipCode { get; set; }

    public string StreetAddress { get; set; }

    public bool IsDefault { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Member Members { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}