// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.Backend.Models.EfModel;

public partial class MembershipLevel
{
    public int Id { get; set; }

    public string LevelName { get; set; }

    public int RequiredAmount { get; set; }

    public int? MonthlyCouponId { get; set; }

    public string Description { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<Coupon> Coupons { get; set; } = new List<Coupon>();

    public virtual ICollection<MemberStat> MemberStats { get; set; } = new List<MemberStat>();

    public virtual ICollection<Member> Members { get; set; } = new List<Member>();

    public virtual Coupon MonthlyCoupon { get; set; }
}