// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.Backend.Models.EfModel;

public partial class MemberStat
{
    public int MemberId { get; set; }

    public int? CurrentLevelId { get; set; }

    public int TotalSpent { get; set; }

    public int TotalPoints { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual MembershipLevel CurrentLevel { get; set; }

    public virtual Member Member { get; set; }
}