// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.Backend.Models.EfModel;

public partial class OfficialPostImage
{
    public int Id { get; set; }

    public int? PostId { get; set; }

    public string ImagePath { get; set; }

    public int? SortOrder { get; set; }

    public virtual OfficialPost Post { get; set; }
}