// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.Backend.Models.EfModel;

public partial class OfficialPostComment
{
    public int Id { get; set; }

    public int OfficialPostId { get; set; }

    public int MembersId { get; set; }

    public string Content { get; set; }

    public int? ParentCommentId { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<OfficialPostComment> InverseParentComment { get; set; } = new List<OfficialPostComment>();

    public virtual Member Members { get; set; }

    public virtual OfficialPost OfficialPost { get; set; }

    public virtual OfficialPostComment ParentComment { get; set; }
}