// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Team.Backend.Models.EfModel;

public partial class OfficialPost
{
    public int Id { get; set; }

    [Display(Name = "標題")]
    [Required(ErrorMessage = "請輸入文章標題")]
    public string Title { get; set; }

    public string SeoTitle { get; set; }

    public string SeoDescription { get; set; }

    [Display(Name = "內容")]
    [Required(ErrorMessage = "請輸入文章內容")]
    public string Content { get; set; }

    [Display(Name = "封面圖片")]
    public string CoverImage { get; set; }

    [Display(Name = "分類")]
    public string Category { get; set; }

    public int? ReadingTime { get; set; }

    [Display(Name = "狀態")]
    public string Status { get; set; }

    [Display(Name = "發布時間")]
    public DateTime? PublishedAt { get; set; }

    [Display(Name = "創建者")]
    public int CreatedBy { get; set; }

    [Display(Name = "創建時間")]
    public DateTime CreatedAt { get; set; }

    [Display(Name = "更新時間")]
    public DateTime? UpdatedAt { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual ICollection<OfficialPostComment> OfficialPostComments { get; set; } = new List<OfficialPostComment>();

    public virtual ICollection<OfficialPostImage> OfficialPostImages { get; set; } = new List<OfficialPostImage>();
}