// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.Backend.Models.EfModel;

public partial class OrderAddress
{
    public int Id { get; set; }

    public int? MemberId { get; set; }

    public string RecipientName { get; set; }

    public string PhoneNumber { get; set; }

    public string AddressType { get; set; }

    public string StoreType { get; set; }

    public string StoreId { get; set; }

    public string ZipCode { get; set; }

    public string FullAddress { get; set; }

    public bool? IsDefault { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Member Member { get; set; }
}