// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.Backend.Models.EfModel;

public partial class OrderNotification
{
    public int Id { get; set; }

    public int? OrderId { get; set; }

    public int? MemberId { get; set; }

    public int? SellerId { get; set; }

    public string Category { get; set; }

    public string Message { get; set; }

    public DateTime SentAt { get; set; }

    public string SendStatus { get; set; }

    public string EmailAddress { get; set; }

    public string EmailStatus { get; set; }

    public DateTime? EmailSentAt { get; set; }

    public int EmailRetry { get; set; }

    public string Channel { get; set; }

    public bool IsDeleted { get; set; }

    public virtual Member Member { get; set; }

    public virtual Order Order { get; set; }

    public virtual Seller Seller { get; set; }
}