// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.Backend.Models.EfModel;

public partial class Payment
{
    public int Id { get; set; }

    public int OrderId { get; set; }

    public string Status { get; set; }

    public string CardNumberLast4 { get; set; }

    public DateTime? TransactionTime { get; set; }

    public string RawRequest { get; set; }

    public string RawResponse { get; set; }

    public string ErrorMessage { get; set; }

    public string SourceIp { get; set; }

    public string MemberAgent { get; set; }

    public bool? HashVerified { get; set; }

    public virtual Order Order { get; set; }
}