// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.Backend.Models.EfModel;

public partial class PointsLog
{
    public int Id { get; set; }

    public int? MemberId { get; set; }

    public string Type { get; set; }

    public int Amount { get; set; }

    public string Note { get; set; }

    public DateTime? ExpiredAt { get; set; }

    public string TransactionId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public string VerificationCode { get; set; }

    public virtual Member Member { get; set; }
}