// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.Backend.Models.EfModel;

public partial class PointsLogError
{
    public int Id { get; set; }

    public int? MemberId { get; set; }

    public string ErrorType { get; set; }

    public string ErrorDetails { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Member Member { get; set; }
}