// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.Backend.Models.EfModel;

public partial class PostComment
{
    public int Id { get; set; }

    public int PostId { get; set; }

    public int MembersId { get; set; }

    public string Content { get; set; }

    public int? ParentCommentId { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<PostComment> InverseParentComment { get; set; } = new List<PostComment>();

    public virtual Member Members { get; set; }

    public virtual PostComment ParentComment { get; set; }

    public virtual Post Post { get; set; }
}