// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Team.Backend.Models.EfModel;

public partial class Post
{
    public int Id { get; set; }

    [Display(Name = "標題")]
    public string Title { get; set; }

    [Display(Name = "內容")]
    public string Content { get; set; }

    [Display(Name = "會員ID")]
    public int MembersId { get; set; }

    [Display(Name = "圖片")]
    public string Image { get; set; }

    [Display(Name = "狀態")]
    public string Status { get; set; }

    [Display(Name = "拒絕原因")]
    public string RejectedReason { get; set; }

    [Display(Name = "建立時間")]
    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? PublishedAt { get; set; }

    public int? ReviewedBy { get; set; }

    [Display(Name = "審核時間")]
    public DateTime? ReviewedAt { get; set; }

    public virtual Member Members { get; set; }

    public virtual ICollection<PostComment> PostComments { get; set; } = new List<PostComment>();

    public virtual ICollection<PostLike> PostLikes { get; set; } = new List<PostLike>();

    public virtual ICollection<PostProduct> PostProducts { get; set; } = new List<PostProduct>();

    public virtual User ReviewedByNavigation { get; set; }
}