// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.Backend.Models.EfModel;

public partial class PostProduct
{
    public int Id { get; set; }

    public int? PostId { get; set; }

    public int? ProductId { get; set; }

    public virtual Post Post { get; set; }

    public virtual Product Product { get; set; }
}