// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.Backend.Models.EfModel;

public partial class ProductAttributeValue
{
    public int Id { get; set; }

    public int? ProductId { get; set; }

    public int? AttributeValueId { get; set; }

    public int Stock { get; set; }

    public string Sku { get; set; }

    public int? SkuGroupId { get; set; }

    public decimal? AdditionalPrice { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual AttributeValue AttributeValue { get; set; }

    public virtual ICollection<CartItem> CartItems { get; set; } = new List<CartItem>();

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual Product Product { get; set; }
}