// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.Backend.Models.EfModel;

public partial class ProductImage
{
    public int Id { get; set; }

    public int ProductId { get; set; }

    public int? SkuId { get; set; }

    public string ImagesUrl { get; set; }

    public int SortOrder { get; set; }

    public virtual Product Product { get; set; }
}