// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.Backend.Models.EfModel;

public partial class RestockNotification
{
    public int Id { get; set; }

    public DateTime SentAt { get; set; }

    public string Sku { get; set; }

    public int SellersId { get; set; }

    public string StockStatus { get; set; }

    public string SendStatus { get; set; }

    public string EmailAddress { get; set; }

    public string EmailStatus { get; set; }

    public DateTime? EmailSentAt { get; set; }

    public int EmailRetry { get; set; }

    public string Channel { get; set; }

    public virtual Seller Sellers { get; set; }
}