// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.Backend.Models.EfModel;

public partial class SellerBankAccount
{
    public int Id { get; set; }

    public int SellersId { get; set; }

    public string BankName { get; set; }

    public string BankCode { get; set; }

    public string AccountName { get; set; }

    public string AccountNumber { get; set; }

    public bool IsDefault { get; set; }

    public bool IsVerified { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Seller Sellers { get; set; }
}