// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.Backend.Models.EfModel;

public partial class Session
{
    public int SessionId { get; set; }

    public int MembersId { get; set; }

    public string DeviceInfo { get; set; }

    public string IpAddress { get; set; }

    public DateTime ExpiresAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime LastActivityAt { get; set; }

    public virtual Member Members { get; set; }
}