// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Team.Backend.Models.EfModel;

public partial class VerificationCode
{
    public int Id { get; set; }

    public int? MembersId { get; set; }

    public string ContactInfo { get; set; }

    public string Type { get; set; }

    public string Code { get; set; }

    public DateTime ExpiresAt { get; set; }

    public bool IsUsed { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Member Members { get; set; }
}